#!/usr/bin/env bash
# ===========================================
# check.sh — Verify symlinks, generated files, and repo status
# ===========================================
# Checks that all symlinks point to the repo, generated files exist,
# and optionally commits any uncommitted changes.

set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

# ------------------------------------
# Load secrets (needed for Claude account checks)
# ------------------------------------

SECRETS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/.secrets"
if [ -f "$SECRETS_FILE" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$SECRETS_FILE"
  set +a
fi

# ------------------------------------
# Helpers
# ------------------------------------

info()    { printf "\033[1;34m%s\033[0m\n" "$1"; }
success() { printf "\033[1;32m%s\033[0m\n" "$1"; }
warn()    { printf "\033[1;33m%s\033[0m\n" "$1"; }

check_symlink() {
  local system_path="$1" expected_target="$2"

  if [ ! -e "$system_path" ]; then
    warn "MISSING: $system_path"
    return
  fi

  if [ -L "$system_path" ]; then
    local actual_target
    actual_target="$(readlink "$system_path")"
    if [ "$actual_target" = "$expected_target" ]; then
      success "OK: $system_path → repo"
    else
      warn "WRONG LINK: $system_path → $actual_target (expected $expected_target)"
    fi
  else
    warn "NOT LINKED: $system_path (run install.sh to link)"
  fi
}

# ------------------------------------
# Check symlink health
# ------------------------------------

echo ""
info "=== Checking symlink status ==="
echo ""

check_symlink "$HOME/.zshrc"                    "$DOTFILES_DIR/shell/.zshrc"
check_symlink "$HOME/.tmux.conf"                "$DOTFILES_DIR/tmux/.tmux.conf"
check_symlink "$HOME/.config/ghostty/config"    "$DOTFILES_DIR/terminal/ghostty/config"
check_symlink "$HOME/.config/nvim"              "$DOTFILES_DIR/editor/nvim"
check_symlink "$HOME/.config/starship.toml"     "$DOTFILES_DIR/prompt/starship.toml"
check_symlink "$HOME/.gitignore"                "$DOTFILES_DIR/git/.gitignore"
check_symlink "$HOME/.config/sesh/sesh.toml"    "$DOTFILES_DIR/tools/sesh.toml"
check_symlink "$HOME/.aerospace.toml"           "$DOTFILES_DIR/tools/aerospace.toml"
check_symlink "$HOME/bin/vpn"                   "$DOTFILES_DIR/tools/vpn"
check_symlink "$HOME/Library/Keyboard Layouts/UA-RU-layout.bundle" "$DOTFILES_DIR/keyboards/UA-RU-layout.bundle"

# ------------------------------------
# Check generated files
# ------------------------------------

echo ""
info "=== Generated files (managed by install.sh) ==="
echo ""

if [ -f "$HOME/.gitconfig" ]; then
  if grep -q "# Generated by dotfiles" "$HOME/.gitconfig" 2>/dev/null; then
    success "OK: ~/.gitconfig (generated)"
  else
    warn "MANUAL: ~/.gitconfig was edited outside install.sh"
  fi
else
  warn "MISSING: ~/.gitconfig (run install.sh)"
fi

if [ -d "$HOME/.aliases.d" ]; then
  count=$(find "$HOME/.aliases.d" -name "*.sh" | wc -l | tr -d ' ')
  success "OK: ~/.aliases.d/ ($count generated files)"
else
  warn "MISSING: ~/.aliases.d/ (run install.sh)"
fi

_local_aliases_dir="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/aliases.d"
if [ -d "$_local_aliases_dir" ]; then
  local_count=$(find "$_local_aliases_dir" -name "*.sh" | wc -l | tr -d ' ')
  success "OK: ~/.config/dotfiles/aliases.d/ ($local_count local files)"
else
  warn "MISSING: ~/.config/dotfiles/aliases.d/ (run install.sh)"
fi

if [ -f "$HOME/.aliases.d/dotfiles.sh" ]; then
  success "OK: ~/.aliases.d/dotfiles.sh (dotfiles listing command)"
else
  warn "MISSING: ~/.aliases.d/dotfiles.sh (run install.sh)"
fi

# ------------------------------------
# Check Claude Code config dirs
# ------------------------------------

echo ""
info "=== Claude Code config dirs ==="
echo ""

if [ -d "$HOME/.claude-personal" ]; then
  if [ -f "$HOME/.claude-personal/settings.json" ]; then
    success "OK: ~/.claude-personal/settings.json"
  else
    warn "MISSING: ~/.claude-personal/settings.json (run install.sh)"
  fi
else
  warn "MISSING: ~/.claude-personal/ (run install.sh)"
fi

if [ -n "${CLAUDE_SYMLINK_ACCOUNT:-}" ]; then
  _ck_config_dir=""
  for i in $(seq 1 99); do
    _ck_name_var="CLAUDE_ACCOUNT_${i}_NAME"; _ck_name="${!_ck_name_var:-}"
    [ -z "$_ck_name" ] && break
    if [ "$_ck_name" = "$CLAUDE_SYMLINK_ACCOUNT" ]; then
      _ck_cfg_var="CLAUDE_ACCOUNT_${i}_CONFIG_DIR"; _ck_config_dir="${!_ck_cfg_var:-}"
      break
    fi
  done
  unset _ck_name_var _ck_name _ck_cfg_var

  if [ -n "$_ck_config_dir" ]; then
    if [ -L "$_ck_config_dir" ] && [ "$(readlink "$_ck_config_dir")" = "$HOME/.claude" ]; then
      success "OK: $CLAUDE_SYMLINK_ACCOUNT config dir → ~/.claude (symlink)"
    elif [ -L "$_ck_config_dir" ]; then
      warn "WRONG SYMLINK: $CLAUDE_SYMLINK_ACCOUNT config dir → $(readlink "$_ck_config_dir") (expected ~/.claude)"
    elif [ -d "$_ck_config_dir" ]; then
      warn "NOT A SYMLINK: $_ck_config_dir is a real directory — run install.sh to convert"
    else
      warn "MISSING: $_ck_config_dir (run install.sh)"
    fi
  else
    warn "CLAUDE_SYMLINK_ACCOUNT=$CLAUDE_SYMLINK_ACCOUNT but no matching CLAUDE_ACCOUNT_N_NAME found"
  fi
  unset _ck_config_dir
fi

# ------------------------------------
# Check keyboard layout (macOS only)
# ------------------------------------

if [ "$(uname -s)" = "Darwin" ]; then
  echo ""
  info "=== Keyboard layout (macOS) ==="
  echo ""

  # Bundle symlink itself is verified above with the other configs.
  # Check if the layout is also active in input sources.
  if defaults read com.apple.HIToolbox AppleEnabledInputSources 2>/dev/null \
      | grep -q "ua_ru_layout"; then
    success "OK: UA–RU–layout (enabled in input sources)"
  else
    warn "NOT ENABLED: UA–RU–layout is installed but not active"
    warn "  → System Settings → Keyboard → Input Sources → + → 'UA–RU–layout'"
  fi
fi

# ------------------------------------
# Check repo for uncommitted changes
# ------------------------------------

echo ""
info "=== Repository status ==="
echo ""

cd "$DOTFILES_DIR"

if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  warn "Not a git repository yet. Run: git init && git add -A && git commit -m 'Initial commit'"
  exit 0
fi

if git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  success "No uncommitted changes."
else
  info "Uncommitted changes detected:"
  git status --short
  echo ""
  printf "Commit these changes? [y/N] "
  read -r answer
  if [[ "$answer" =~ ^[Yy]$ ]]; then
    git add -A
    git commit -m "Update dotfiles ($(date +%Y-%m-%d))"
    success "Changes committed!"
  else
    warn "Changes left uncommitted."
  fi
fi
